name: Update README Data

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
        shell: bash

      - name: Curl for GitHub Actions
        uses: sozo-design/curl@v1.0.2
        with:
          args: '-s -o champs.json https://thebsw.github.io/champs.json'

      - name: Process JSON Data with jq
        uses: sergeysova/jq-action@v2
        with:
          script: 'to_entries | map("* \(.key): \(.value)") | join("\n")'
        id: processed_data

      - name: Update champs.json
        run: |
          echo "${{ steps.processed_data.outputs.output }}" > champs.json
          git add champs.json
          git commit -m "Update champs.json" || true
          git push
        shell: bash

      - name: Upgrade GitHub CLI
        uses: philip-gai/upgrade-gh-cli@v1
